Integration tests for GraphQL were created
vpetrovaa/note-service pull request #22
Opened 2023-06-09 11:09 UTC by vpetrovaa

2023-06-09 11:16 UTC, vpetrovaa commented
@h1alexbel is it a good practise for GraphQL integration tests to do like this:
Test to verify that we deleted the entity from db:
1. Create the entity and get this object
2. Get received id
3. Delete by this id
4. Call the existById method and assert false result
And all this steps in one test?
So on the one hand all tests are dont depend of each other and data that already exists in db, but on the other hand they become very complex

2023-06-12 08:06 UTC, h1alexbel requested changes
@vpetrovaa check my comments

2023-06-12 08:06 UTC, h1alexbel commented on pom.xml
> +		<dependency>
compile dependencies should be separated with test one

2023-06-12 08:10 UTC, h1alexbel commented
> @h1alexbel is it a good practise for GraphQL integration tests to do like this: Test to verify that we deleted the entity from db:
> 
> 1. Create the entity and get this object
> 2. Get received id
> 3. Delete by this id
> 4. Call the existById method and assert false result
>    And all this steps are in one test?
>    So on the one hand all tests don't depend of each other and data that already exists in db, but on the other hand they become very complex

You should start the container in some class, that will be a parent for all other tests with database support for integration testing
then execute some logic, assert it inside your test
and then method (in the parent class), for container destroy should be invoked

2023-06-13 12:32 UTC, h1alexbel approved these changes

2023-06-13 12:32 UTC, merged